### PR TITLE
Updated equinix metal manual docs

### PR DESCRIPTION
**Pull request by markcallen**
Added info about creating a kind cluster for the manager cluster.  

Added info about the ssh-key needing to be created in the console for the project.

### CODE REVIEW

**Comment by rossf7** [comment]
@markcallen Could you add a signoff to your commit to fix the DCO check?

LGTM (I don't have approval rights)

@leonardpahlke @nikimanoledaki PTAL

**Comment by markcallen** [comment]
@rossf7 updated for signoff.

**Review by rossf7 — APPROVED** [review]

**Review by nikimanoledaki — APPROVED** [review]
LGTM, thank you @markcallen @rossf7 @leonardpahlke!

**Comment by nikimanoledaki** [comment]
Unfortunately the PR is still blocked because the commit must be verified e.g. with GPG:

> The base branch requires all commits to be signed. [Learn more about signing commits.](https://docs.github.com/articles/about-gpg/)

**Comment by markcallen** [comment]
@nikimanoledaki added gpg

**Pull request merged**
