### PR TITLE
Revert changes for dedicated documentation website

### PR DESCRIPTION
**Pull request by guidemetothemoon**
#### What type of PR is this?
kind/documentation

#### What this PR does / why we need it:
Reverting changes for having a dedicated documentation website. All documentation is located in the docs folder at the root of the repo. Markdown linter fixes and metadata for Hugo pages is preserved for the future place where this content will be available as part of the website.

#### Which issue(s) this PR fixes:
Related to #89

### CODE REVIEW

**Review by nikimanoledaki — APPROVED** [review]
Thank you! We'll find a good home for these docs, eventually... 😅 

Also thank you for preserving git history with `git mv `! 🚀

**Comment by nikimanoledaki** [comment]
Huh, I _should_ be able to merge this PR (and was able to do so previously) but that's no longer possible. It requires a review from TAG ENV Leads 🤔

**Comment by guidemetothemoon** [comment]
I'm not sure who added the TAG ENV leads as reviewers - it wasn't me at least and I'm not sure if it's really needed for every PR? Maybe this is a consequence of some new governance rule that I'm not aware of...

@leonardpahlke @mkorbi please comment if you know anything about this change. I can't approve my own PR so one of you needs to review it as well.

**Comment by rossf7** [comment]
> I'm not sure who added the TAG ENV leads as reviewers - it wasn't me at least and I'm not sure if it's really needed for every PR? Maybe this is a consequence of some new governance rule that I'm not aware of...

@guidemetothemoon this is due to the CODEOWNERS rules added in #82  There are a list of known file extensions that Green Reviews leads can approve and `*` that needs approval from TAG ENV leads.

The problem is reverting includes changes such as `.toml` that are not in the list. Once this is merged the rules will be correct again.

@leonardpahlke @mkorbi Can one of you review? 

If this happens often we might need to look at the CODEOWNERS rules again.






https://github.com/cncf-tags/green-reviews-tooling/pull/82

**Review by rossf7 — APPROVED** [review]

**Comment by nikimanoledaki** [comment]
Hey @rossf7, thank you for clarifying this! ☺️ What is the benefit of having this distinction? Could we move everything under @cncf-tags/tag-env-wg-green-reviews-leads? 🤔

**Review by leonardpahlke — COMMENTED** [review]
https://github.com/cncf-tags/green-reviews-tooling/issues/65 -- is still under discussion, and therefore it's not clear how many changes the PR would revert. Let's wait until the discussion is finalized.

**Comment by AntonioDiTuri** [comment]
Merging as discussed in https://github.com/cncf-tags/green-reviews-tooling/issues/65#issuecomment-2158363106

**Pull request merged**
